package:
  name: kaldifst
  version: "1.3"

source:
  path: "{{ environ.get('KALDIFST_ROOT_DIR') }}"

build:
  number: 0
  string: py{{ environ.get('KALDIFST_PYTHON_VERSION') }}
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }} # [win]
    - {{ compiler('cxx') }} # [win]

  host:
    - anaconda-client
    - conda-build
    - cmake
    - python
  run:
    - python

about:
  home: https://github.com/k2-fsa/kaldifst
  license: Apache V2
  license_file: LICENSE
  summary: Python wrapper for OpenFST and its extensions from Kaldi
  description: |
    Python wrapper for OpenFST and its extensions from Kaldi
