
all:
	python3 ./quick-start.py
	python3 ./quick-start-2.py
	python3 ./quick-start-3.py

clean:
	$(RM) quick-start.svg quick-start.gv binary.fst
	$(RM) quick-start-2.svg quick-start-2.gv binary-2.fst
	$(RM) quick-start-3.svg quick-start-3.gv

