
all:
	$(MAKE) -C add_self_loops
	$(MAKE) -C arcsort
	$(MAKE) -C compose
	$(MAKE) -C connect
	$(MAKE) -C determinize
	$(MAKE) -C determinizestar
	$(MAKE) -C draw
	$(MAKE) -C equal_align
	$(MAKE) -C fstcompile
	$(MAKE) -C invert
	$(MAKE) -C make_linear_acceptor
	$(MAKE) -C minimize
	$(MAKE) -C minimize_encoded
	$(MAKE) -C reverse
	$(MAKE) -C rmepsilon

clean:
	$(MAKE) -C add_self_loops clean
	$(MAKE) -C arcsort clean
	$(MAKE) -C compose clean
	$(MAKE) -C connect clean
	$(MAKE) -C determinize clean
	$(MAKE) -C determinizestar clean
	$(MAKE) -C draw clean
	$(MAKE) -C equal_align clean
	$(MAKE) -C fstcompile clean
	$(MAKE) -C invert clean
	$(MAKE) -C make_linear_acceptor clean
	$(MAKE) -C minimize clean
	$(MAKE) -C minimize_encoded clean
	$(MAKE) -C reverse clean
	$(MAKE) -C rmepsilon clean
