
all:
	$(MAKE) -C fstcompile
	$(MAKE) -C arcsort
	$(MAKE) -C compose
	$(MAKE) -C determinize
	$(MAKE) -C determinizestar
	$(MAKE) -C draw

clean:
	$(MAKE) -C fstcompile clean
	$(MAKE) -C arcsort clean
	$(MAKE) -C compose clean
	$(MAKE) -C determinize clean
	$(MAKE) -C determinizestar clean
	$(MAKE) -C draw clean
