
all:
	$(MAKE) -C fstcompile
	$(MAKE) -C arcsort
	$(MAKE) -C compose
	$(MAKE) -C determinize
	$(MAKE) -C determinizestar
	$(MAKE) -C draw
	$(MAKE) -C connect
	$(MAKE) -C invert
	$(MAKE) -C reverse
	$(MAKE) -C minimize

clean:
	$(MAKE) -C fstcompile clean
	$(MAKE) -C arcsort clean
	$(MAKE) -C compose clean
	$(MAKE) -C determinize clean
	$(MAKE) -C determinizestar clean
	$(MAKE) -C draw clean
	$(MAKE) -C connect clean
	$(MAKE) -C invert clean
	$(MAKE) -C reverse clean
	$(MAKE) -C minimize clean
